<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lth</string>
	</array>
	<key>name</key>
	<string>LeatherScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>(?&lt;!\\)"</string>
			<key>name</key>
			<string>string.quoted.double.lth</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.lth</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.lth</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(type)\s+(\w+)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>if</string>
			<key>name</key>
			<string>keyword.lth</string>
		</dict>
		<dict>
			<key>match</key>
			<string>then</string>
			<key>name</key>
			<string>keyword.lth</string>
		</dict>
		<dict>
			<key>match</key>
			<string>else</string>
			<key>name</key>
			<string>keyword.lth</string>
		</dict>
		<dict>
			<key>match</key>
			<string>match</string>
			<key>name</key>
			<string>keyword.lth</string>
		</dict>
		<dict>
			<key>match</key>
			<string>case</string>
			<key>name</key>
			<string>keyword.lth</string>
		</dict>
		<dict>
			<key>match</key>
			<string>begin</string>
			<key>name</key>
			<string>keyword.lth</string>
		</dict>
		<dict>
			<key>match</key>
			<string>end</string>
			<key>name</key>
			<string>keyword.lth</string>
		</dict>
		<dict>
			<key>match</key>
			<string>simple</string>
			<key>name</key>
			<string>keyword.lth</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.lth</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.lth</string>
				</dict>
			</dict>
			<key>match</key>
			<string>`(\w+)\s+(of)\s+</string>
		</dict>
		<dict>
			<key>match</key>
			<string>`\w+\s+</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.lth</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w+)\s+:\s+</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\w+</string>
			<key>name</key>
			<string>variable.lth</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.lth</string>
	<key>uuid</key>
	<string>4d06c48f-6167-4c6b-b59b-7ce5932ef552</string>
</dict>
</plist>
